drop table note if exists;
drop table note_agent if exists;
drop table note_book if exists;

create table note (
id bigint generated by default as identity,
text varchar(255) not null,
notebook bigint,
primary key (id)
);

create table note_agent (
id bigint generated by default as identity,
api_key varchar(255) not null,
name varchar(255) not null,
notebook bigint,
primary key (id)
);

create table note_book (
id bigint generated by default as identity,
name varchar(255) not null,
primary key (id)
);

alter table note
    add constraint UK_mibtatst9ku0a2m6ltvlmbijs unique (text);

alter table note_agent
    add constraint UK_fimik53p25wgbd6ye94mrb2ld unique (name);

alter table note_book
    add constraint UK_qe00sw2x0prjmxu9jm4oyy6v3 unique (name);

alter table note
    add constraint FKsoip7l025uhdol5yuav0uu3og
    foreign key (notebook)
    references note_book;

alter table note_agent
    add constraint FKnqo5ax794gfhyfcgvn0f64o88
    foreign key (notebook)
    references note_book;